import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'hello': 'Hello',
          'good_morning': 'Good morning',
          'sign_in': 'Sign In',
          'register': 'Register',
          'password': 'Password',
          'phone_number': 'Phone Number',
          'full_name': 'Full Name',
          'email': 'Email',
          'address': 'Address',
          'home': 'Home',
          'search': 'Search',
          'featured_properties': 'Featured Properties',
          'see_all': 'See All',
          'most_viewed': 'Most Viewed',
          'house': 'House',
          'office': 'Office',
          'villa': 'Villa',
          'commercial': 'Commercial',
          'apartment': 'Apartment',
          'lands': 'Lands',
          'favorites': 'Favorites',
          'properties': 'Properties',
          'profile': 'Profile',
          'language': 'Language',
          'my_profile': 'My Profile',
          'edit_profile': 'Edit Profile',
          'my_property': 'My Property',
          'sell': 'Sell',
          'rent': 'Rent',
          'filter': 'Filter',
          'for_sell': 'For Sell',
          'for_rent': 'For Rent',
          'clear_filter': 'Clear Filter',
          'property_type': 'Property Type',
          'budget': 'Budget',
          'min': 'Min',
          'max': 'Max',
          'area': 'Area',
          'apply_filter': 'Apply Filter',
          'featured': 'Featured ',
          'About this property :': 'About this property :'
        },
        'ar': {
          'hello': 'مرحبًا',
          'good_morning': 'صباح الخير',
          'sign_in': 'تسجيل الدخول',
          'register': 'التسجيل',
          'password': 'كلمة المرور',
          'phone_number': 'رقم الهاتف',
          'full_name': 'الاسم الكامل',
          'email': 'البريد الإلكتروني',
          'address': 'العنوان',
          'home': 'الرئيسية',
          'search': 'بحث',
          'featured_properties': 'العقارات المميزة',
          'see_all': 'عرض الكل',
          'most_viewed': 'الأكثر مشاهدة',
          'House': 'منزل',
          'Office': 'مكتب',
          'Villa': 'فيلا',
          'Commercial': 'تجاري',
          'Apartment': 'شقة',
          'Lands': 'أرض',
          'favorites': 'المفضلة',
          'properties': 'العقارات',
          'profile': 'الملف الشخصي',
          'language': 'اللغة',
          'my_profile': 'ملفي الشخصي',
          'edit_profile': 'تعديل الملف الشخصي',
          'my_property': 'عقاري',
          'sell': 'بيع',
          'rent': 'إيجار',
          'filter': 'فلتر',
          'for_sell': 'للبيع',
          'for_rent': 'للإيجار',
          'clear_filter': 'مسح الفلتر',
          'property_type': 'نوع العقار',
          'budget': 'الميزانية',
          'min': 'الحد الأدنى',
          'max': 'الحد الأعلى',
          'area': 'المساحة',
          'apply_filter': 'تطبيق الفلتر',
          'featured': 'مميز',
          'About this property :': ' :عن العقار'
        },
        'fr': {
          'hello': 'Bonjour',
          'good_morning': 'Bonjour',
          'sign_in': 'Se connecter',
          'register': "S'inscrire",
          'password': 'Mot de passe',
          'phone_number': 'Numéro de téléphone',
          'full_name': 'Nom complet',
          'email': 'Email',
          'address': 'Adresse',
          'home': 'Accueil',
          'search': 'Rechercher',
          'featured_properties': 'Propriétés en vedette',
          'see_all': 'Voir tout',
          'most_viewed': 'Les plus consultés',
          'house': 'Maison',
          'office': 'Bureau',
          'villa': 'Villa',
          'commercial': 'Commercial',
          'apartment': 'Appartement',
          'lands': 'Terrains',
          'favorites': 'Favoris',
          'properties': 'Propriétés',
          'profile': 'Profil',
          'language': 'Langue',
          'my_profile': 'Mon profil',
          'edit_profile': 'Modifier le profil',
          'my_property': 'Ma propriété',
          'sell': 'Vendre',
          'rent': 'Louer',
          'filter': 'Filtrer',
          'for_sell': 'À vendre',
          'for_rent': 'À louer',
          'clear_filter': 'Effacer le filtre',
          'property_type': 'Type de propriété',
          'budget': 'Budget',
          'min': 'Min',
          'max': 'Max',
          'area': 'Surface',
          'apply_filter': 'Appliquer le filtre',
          'featured': 'Vedette',
          'About this property :': 'À propos de cette propriété :'
        },
      };
}
